# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_auto_20160413_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='attributes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
