# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20160304_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='schoolCode',
            field=models.CharField(default='E', max_length=1),
            preserve_default=False,
        ),
    ]
