# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20160304_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='creditNum',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='class',
            name='deptID',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='class',
            name='numPrereqs',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='class',
            name='schoolCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.School'),
        ),
        migrations.AlterField(
            model_name='class',
            name='semOffered',
            field=models.SmallIntegerField(default=2),
        ),
    ]
