# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20160226_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('schoolCode', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('schoolName', models.CharField(max_length=60)),
                ('listOfClasses', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='class',
            name='listOfPrereqs',
            field=models.TextField(null=True),
        ),
    ]
