# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_major_schoolcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='schoolCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.School'),
        ),
    ]
