# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20160307_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='listOfPrereqs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
