# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_auto_20160307_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='creditsToGraduate',
            field=models.SmallIntegerField(default=120),
        ),
    ]
