# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_auto_20160325_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='attributes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='attributes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='attributes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
