# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_auto_20160413_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='class',
            name='description',
        ),
        migrations.RemoveField(
            model_name='major',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='major',
            name='description',
        ),
        migrations.RemoveField(
            model_name='school',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='school',
            name='description',
        ),
    ]
